name: Daily Hot News Push

on:
  schedule:
    # 每天 UTC 时间 01:00 运行，即北京时间 09:00
    - cron: '0 1 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run hot news script
      env:
        FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
        NEWRANK_COOKIE: ${{ secrets.NEWRANK_COOKIE }}  
      run: |
        python main.py
