name: Daily Hot News Push

on:
  schedule:
      # 设置多个触发时间确保执行
    - cron: '0 2 * * *'   # 主要触发：UTC 02:00 = 北京时间 10:00
    - cron: '30 2 * * *'  # 备用触发：UTC 02:30 = 北京时间 10:30
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install playwright
        playwright install chromium
        playwright install-deps

    - name: Run hot news script
      env:
        FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
        NEWRANK_COOKIE: ${{ secrets.NEWRANK_COOKIE }}  
      run: |
        python main.py
