name: Daily Hot News Push

on:
  schedule:
        # 设置提前2小时，应对GitHub延迟
    - cron: '0 0 * * *'   # 主要触发：UTC 00:00 = 北京时间 08:00
    - cron: '30 0 * * *'  # 备用触发：UTC 00:30 = 北京时间 08:30
    - cron: '0 1 * * *'   # 二次备用：UTC 01:00 = 北京时间 09:00
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install playwright
        playwright install chromium
        playwright install-deps

    - name: Run hot news script
      env:
        FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
        NEWRANK_COOKIE: ${{ secrets.NEWRANK_COOKIE }}  
      run: |
        python main.py
